spring.application.name=auction

# ================== DATABASE ==================
spring.datasource.url=jdbc:mysql://localhost:3306/auction_db
spring.datasource.username=root
spring.datasource.password=

# ================== JPA ==================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# # ================== JWT ==================
app.jwt.secret=secret_key_22130014_auction_app_2026
app.jwt.expiration=86400000

# ================== SERVER ==================
server.port=8080

# ================== Cloudinary ==================
cloudinary.cloud_name=dhzcnonq1
cloudinary.api_key=992832638167997
cloudinary.api_secret=_NIAsc4c8jMq0QgWlBwviwI6c2g
